threshold_counter_road_sign: 20
distance_to_road_sign_threshold: 500
x_pos_road_sign_threshold: 550
y_pos_road_sign_threshold: 270
thresh_road_sign: 195
max_val: 255

PID_RACE_10:
  Linear:
    kp: 0.7
    ki: 0
    kd: 0.01
  Angular:
    kp: 0.12
    ki: 0
    kd: 0.1

PID_RACE_20:
  Linear:
    kp: 0.65
    ki: 0
    kd: 0.03
  Angular:
    kp: 0.06
    ki: 0
    kd: 0.05

PID_RACE_25:
  Linear:
    kp: 0.55
    ki: 0
    kd: 0.05
  Angular:
    kp: 0.03
    ki: 0
    kd: 0.001

PID_RACE_30:
  Linear:
    kp: 0.45
    ki: 0
    kd: 0.07
  Angular:
    kp: 0.01
    ki: 0
    kd: 0.0005

PID_URBAN:
  Linear:
    kp: 0.7
    ki: 0
    kd: 0.01
  Angular:
    kp: 0.15
    ki: 0
    kd: 0.2
