float32[] left_lane_x_real
float32[] left_lane_y_real

float32[] right_lane_x_real
float32[] right_lane_y_real

# float32[] middle_lane_x_real
# float32[] middle_lane_y_real

int16 left_lane_x_top
int16 left_lane_x_bottom
int16 left_lane_y_top
int16 left_lane_y_bottom

int16 middle_lane_x_top
int16 middle_lane_x_bottom
int16 middle_lane_y_top
int16 middle_lane_y_bottom

int16 right_lane_x_top
int16 right_lane_x_bottom
int16 right_lane_y_top
int16 right_lane_y_bottom

float32 target_x_left
float32 target_y_left
float32 target_x_right
float32 target_y_right

bool can_be_intercepted